### ISSUE TITLE
Regarding Using The List? 

### ISSUE THREAD

**Issue by Phone-Metal** [pallebone/StrictBlockPAllebone#1]
Hi Firstly Thanks For Alot For The List And Instructions :3
Secondly Holy! That's Alot Of IP's :D 
 Can I Use The List In My Script ? I'll Give Credits To You And Link It Back To This github page =)

**Comment by pallebone** [comment]
Hi Phone-Metal,

The list is totally open,sans,libre and can be used in any way that you see fit, modified however you want, and changed up however you like/forked etc.

The list is created by me for the community with no strings attached.

Please enjoy :)

Kind regards
Pete
