### ISSUE TITLE
Invalid IP

### ISSUE THREAD

**Issue by orzel** [pallebone/StrictBlockPAllebone#4]
Hello.
There's currently an invalid IP in the list: 223.151.2487.180
That prevents parsing.

**Comment by pallebone** [comment]
Hi Orzel,

Thank you for this report. 
This was in error, the correct IP when i rechecked the logs was 223.151.248.180

I have corrected the IP and uploaded a new version. Please let me know if you have further issues.

Kind regards
Pete

**Comment by orzel** [comment]
It now works again, thanks !

**Comment by orzel** [comment]
No more issues :)
